module.exports = {
    "checkShootHit": "0",
    "playerMovement": "1",
    "playerSetupPlayer": "2",
    "playerCreated": "3",
    "playerEnemyCreated": "4",
    "playerDisconnect": "5",
    "playerUpdatePosition": "6",
    "playerEnemyUpdatePosition": "7",
    "playerUpdateRotation": "8",
    "playerAttack": "9",
    "enemyShoot": "10",
    "updatePlayersStatus": "a",
    "updateCurrentEquipment": "b",
    "setupEquipment": "c",
    "getEquipment": "d",

    "setupBullet":"h",
    "getBullet":"g",
    
    "playerJoinGame": "z",
    "playerJoinRoom": "y",
    "playerCannotJoinRoom": "f",
    "countdown": "x",
    "finishCountdown": "w",
    "startGame": "v",
    "moveSafeArea": "u",
    "warnSafeArea": "t",
    "playerOutSafeArea": "s",
    "playerBackInSafeArea": "r",
    "updateRoom": "q",
    "playerDie": "p",
    "updatePlayerKill": "o",
    "getVictimData": "n",
    "playerLeaveRoom": "m",
    "updateNumberOfAlivePlayer": "e",
    "playerLoadFinish": "l",
    "playerWin": "k"
}