module.exports = {
    "checkShootHit":"0",
    "playerMovement": "1",
    "playerNewPlayer": "2",
    "playerCreated": "3",
    "playerEnemyCreated": "4",
    "playerDisconnect": "5",
    "playerUpdatePosition":"6",
    "playerEnemyUpdatePosition":"7",
    "playerUpdateRotation":"8",
    "playerAttack":"9",
    "enemyShoot":"10",
    "updatePlayersStatus":"a",
    "updateCurrentEquitment":"b",
    "setupEquitment":"c",
    "getEquitment":"d",
}